SELECT * FROM brainschema.scans;
insert into scans values (1, "/1.jpg", null);
insert into scans values (2, "/2.jpg", null);
insert into scans values (3, "/3.jpg", null);
insert into scans values (4, "/4.jpg", null);
insert into scans values (5, "/5.jpg", null);
insert into scans values (6, "/6.jpg", null);
insert into scans values (7, "/7.jpg", null);
insert into scans values (8, "/8.jpg", null);
insert into scans values (9, "/9.jpg", null);
insert into scans values (10, "/10.jpg", null);
